[versions]
byetrack = "1.1.4"
agp = "8.13.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"

[libraries]
byetrack = { module = "com.github.timchr42:byetrack", version.ref = "byetrack" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
guavaListenableFuture = { module = "com.google.guava:listenablefuture", version = "1.0" }
nullaway = { module = "com.uber.nullaway:nullaway", version = "0.10.18" }
mockitoCore4 = { module = "org.mockito:mockito-core", version = "4.8.0" }
guavaAndroid = { module = "com.google.guava:guava", version = "31.1-android" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

